version: '3.9'

services:
  django:
    build: .
    container_name: django_app
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/django_app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/django_app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always
