# Generated by Django 5.2 on 2025-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='due', max_length=10),
        ),
    ]
