# Generated by Django 5.2 on 2025-04-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
