# Generated by Django 5.2 on 2025-04-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_purchase_quantity_alter_installment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='first_installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', editable=False, max_length=10),
        ),
    ]
