# Generated by Django 5.2 on 2025-04-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_purchase_first_installment_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_number']},
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='installment_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('purchase', 'installment_number')},
        ),
    ]
