# Generated by Django 5.2 on 2025-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_installment_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
