# Generated by Django 5.2 on 2025-04-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_installment_due_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.IntegerField(),
        ),
    ]
