# Generated by Django 5.2 on 2025-04-17 19:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_installment_due_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
